/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUVJcVg0dld6TEcxZTRQRzFpZ25XeTkrRVhiNEU0NzU1NTNxYTJPS25Iaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTDNITENsWFdGSks2bDBNeGcxaHZNeGlUSFVQa0s4V29WUW1XUW5jMWUwZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJS1VLMTR5U1g5bHZ2MDdET0JIbDhPNWgxTXl5djhCVXpMNlpkVSs1UW5RPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJMMm1VU25RREJsaEZ1TWh2Q2NpVHhkWHNMV0R6YW0xRnZLa1pjUGIybDBnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFJWW16dXNaVTJtbjZhK1NMcW9EUmNMS0x5a3dvZllXVmRSVGJXVXBXRXc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iml0dzJ0TWFVMDRaNEdhSHFsQnI3bGJxcDZWSzRlbUIwSy8rRlVObXI5eXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0ExeEpuZXNpUjhpY3ZvMWk4WXdJR0NqNHNSQU14a3JyMTcrSFM1bnBtaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTERrSjY2TDNsVHlDVVdQRG1zYXdBSnQzMjhVMGxZWE45N1A1aDc3SnVVST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InREcERrNmlRSndtU1dUcDcwYVhoOUx2VlNhV0tJOUtab2lQRWxoMy9NQVdkZ0Y4bUt3ZDFxSTN1RFVLdjA5SWNsZVp4dHJMOC9mcy85UmgreXhnRWhRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAyLCJhZHZTZWNyZXRLZXkiOiJFZFZwdFFiMDRhQnUwS0NMNW8xckpjblJTWWlDUFVEL0d3emN3Z3o2WjFVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDgxMjE2NjI2OTdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODBFNDFCMDFCRDc1RTlENzhGRkU4MEM4NDAxRUNGMDEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODY1MzY4MH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0ODEyMTY2MjY5N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJEMUIyQ0YxRTFDQUQxODUyQ0IwOTM5NjA2QTNBOURDQSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI4NjUzNjgyfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJBb2dHSkJDOVJjZVZ3UVlvSWk1ZWxnIiwicGhvbmVJZCI6IjM0ZGM5ZGJmLTE5NjYtNDUzMi05MDVmLWVlYjZmZGZmYTJhNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJIRFFPZ1BDR1hOTmlDUHVXRGlheEp0WkYxMWM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiL3BMeFJWOTM2a2x4bW5waE9XQ0RLS0FidlJrPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjlYTE1EQ05HIiwibWUiOnsiaWQiOiIyMzQ4MTIxNjYyNjk3OjEwQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IuOAjvCdkKDwnZCe8J2Qq/CdkJrwnZCl8J2QneKcruOAjyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTFByaHJVSEVOWFNwTGdHR0FZZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiM3RscDVHY25WOGdEUUwrRTUybEFNcFBMejRnbEpzUkdUeDdOakc5WkNsbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoielNDbTBybjF5T1NNNTlCaWYwNjNCUExhRkdYQUVZUTJiK0NJOG5mbzU1TEkveXhWSHlYY0lQOTZ0RGhLTlVUUTdQKzhJaXNVTSt0STlDcDJpN1EzQnc9PSIsImRldmljZVNpZ25hdHVyZSI6ImFwZFpZWVMrQjN5a2tlbnVydGIxdm9qUHpSREFGV05RSDVMRFNUUlB1eGRGWHhLM2JpVE0yQzNKdmsxQ2dzdjA1Sm9KWjJ3ejVhTXh1RVFjUjBGWGhBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODEyMTY2MjY5NzoxMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJkN1phZVJuSjFmSUEwQy9oT2RwUURLVHk4K0lKU2JFUms4ZXpZeHZXUXBhIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI4NjUzNjY3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUQyWCJ9';

const prefix = process.env.PREFIX || '/';
const mycode = process.env.CODE || "234";
const author = process.env.STICKER_AUTHOR || 'gerald';
const packname = process.env.PACKNAME || 'gerald';
const dev = process.env.DEV || '2348121662697';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝗠𝗔𝗧𝗘𝗢 𝗖𝗛𝗔𝗧';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'false';
const antidelete = process.env.ANTIDELETE || 'false';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
